server:
  port: 80
spring:
  application:
    name: cloud-consumer-openfeign-order
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
    openfeign:
      circuitbreaker:
          enabled: true
          group:
            enabled: true
      compression:
        request:
          enabled: true
          mime-types: text/xml,application/xml,application/json
          min-request-size: 2048
        response:
          enabled: true
      httpclient:
        hc5:
          enabled: true
      client:
        config:
          default:
            connect-timeout: 3000
            read-timeout: 3000
            # 对于不同服务自定义不同超时时间, 例如对cps
            # config:
            #   cloud-payment-service:
            #     connectTimeout: 3000
            #     readTimeout: 3000

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        failure-rate-threshold: 50
#        sliding-window-type: count_based
#        sliding-window-size: 6
#        minimum-number-of-calls: 6
#        automatic-transition-from-open-to-half-open-enabled: true
#        wait-duration-in-open-state: 5s
#        permitted-number-of-calls-in-half-open-state: 2
#        record-exceptions:
#          - java.lang.Exception
#    instances:
#      cloud-payment-service:
#        baseConfig: default

resilience4j:
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 2
        max-wait-duration: 1s
    instances:
      cloud-payment-service:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeout-duration: 20s
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 30
        sliding-window-type: time_based
        sliding-window-size: 2
        minimum-number-of-calls: 2
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        record-exceptions:
          - java.lang.Exception
    instances:
      cloud-payment-service:
        baseConfig: default


logging:
  level:
    com:
      atguigu:
        cloud:
          apis:
            com.atguigu.cloud.apis.PayFeignApi: DEBUG


# zipkin configuration
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0