server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: localhost:8848 # configure nacos addr