server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: localhost:8848
# need to configure here the microservices to be requested
service-url:
  nacos-user-service: http://nacos-payment-provider